import { expect, Page, test as pwt } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { LinkChecker } from './linkinatorShim';
import { resolveBasicAuthProfile, type BasicAuthProfile } from '@utils/basicAuth';

import { linkCheckConfig } from '@config/feature-config/linkCheck.config';
import { buildDir } from '@root/playwright.config';

export type LinkCheckOverrides = {
  /** Crawl beyond the initial page (can make scans much bigger). */
  recurse?: boolean;
  /** Check only links on the same origin as the start URL. */
  sameOriginOnly?: boolean;
  /** Max concurrent link checks. Lower this if you see rate limiting. */
  concurrency?: number;
  /** Per-link timeout in milliseconds. */
  timeoutMs?: number;

  /** Links to skip entirely (substring match). */
  skippedLinks?: Record<string, boolean>;

  /** Treat these HTTP status codes as acceptable (won't fail soft assertion). */
  allowedStatusCodes?: Record<number, boolean>;

  /** Include non-broken links in the report output. */
  includeOkLinksInReport?: boolean;
  /** Max number of OK links to include in report (when includeOkLinksInReport=true). */
  okLinksReportLimit?: number;
  /** Max number of broken links to include in report. */
  brokenLinksReportLimit?: number;

  /**
   * Optional Basic Auth profile for crawler requests.
   * - `true`: auto-resolve global basic auth from env
   * - `'USER_KEY'`: resolve per-user basic auth credentials
   * - `false`: disable auth header injection for this run
   */
  basicAuth?: BasicAuthProfile | false;
};

function toOrigin(url: string): string {
  return new URL(url).origin;
}

function shouldSkipByPattern(url: string, patterns: Record<string, boolean>): boolean {
  return Object.entries(patterns).some(([pattern, enabled]) => enabled && url.includes(pattern));
}

function formatFailureDetails(details: unknown): string {
  if (!details) return '';
  if (typeof details === 'string') return details;
  if (Array.isArray(details)) {
    const statuses = details
      .map((d: any) => (typeof d?.status === 'number' ? d.status : undefined))
      .filter((s: any): s is number => typeof s === 'number');
    if (statuses.length) return `status ${statuses.join(', ')}`;
    return '';
  }
  if (typeof details === 'object') return '';
  return String(details);
}

function buildAuthorizationHeaderValue(username: string, password: string): string {
  return `Basic ${Buffer.from(`${username}:${password}`, 'utf8').toString('base64')}`;
}

function buildCookieHeaderValue(
  cookies: Array<{ name: string; value: string }> | undefined
): string | undefined {
  if (!cookies?.length) return undefined;
  const pairs = cookies
    .filter(c => c.name)
    .map(c => `${c.name}=${c.value}`)
    .filter(Boolean);
  return pairs.length ? pairs.join('; ') : undefined;
}

async function resolveCrawlerHeaders(
  page: Page,
  startUrl: string,
  opts: {
    basicAuthOverride?: BasicAuthProfile | false;
    sameOriginOnly: boolean;
  }
): Promise<Record<string, string> | undefined> {
  const headers: Record<string, string> = {};

  // Reuse current browser-context session cookies for same-origin scans.
  if (opts.sameOriginOnly) {
    try {
      const cookies = await page.context().cookies(startUrl);
      const cookieHeader = buildCookieHeaderValue(cookies);
      if (cookieHeader) {
        headers.Cookie = cookieHeader;
      }
    } catch {
      // ignore cookie resolution errors
    }
  }

  // Attach Basic Auth unless explicitly disabled via override.
  if (opts.basicAuthOverride !== false) {
    const profile: BasicAuthProfile =
      opts.basicAuthOverride === undefined || opts.basicAuthOverride === true
        ? true
        : opts.basicAuthOverride;

    try {
      const creds = resolveBasicAuthProfile(profile);
      if (creds) {
        headers.Authorization = buildAuthorizationHeaderValue(creds.username, creds.password);
      }
    } catch {
      // No basic auth credentials available - skip silently.
    }
  }

  return Object.keys(headers).length ? headers : undefined;
}

async function attachReportsLocationNote(reportDir: string): Promise<void> {
  try {
    const note = [
      '# Link check reports location',
      '',
      `More detailed link check reports are available in: \`${reportDir}\``,
      '',
      'What you can find there:',
      '- per-page reports generated by each check run (including `link-check_<url>_<timestamp>.md` and matching JSON files),',
      '- aggregated summary reports generated in teardown for the whole run:',
      '  - `link-check-report.json`',
      '  - `link-check-report.md`',
      '  - `link-check-report.pdf`',
    ].join('\n');

    await pwt.info().attach('link-check-reports-location.md', {
      body: Buffer.from(note, 'utf8'),
      contentType: 'text/markdown',
    });
  } catch {
    // ignore attachment errors to avoid hiding real results
  }
}

/**
 * Runs link validation for the current page URL and stores per-page report artifacts under
 * `build/artifacts/linkCheck/`.
 *
 * Link issues are always reported as soft assertions — the test continues even when issues are found.
 *
 * @param page Playwright Page (must already be navigated; page.url() must be non-empty)
 * @param override Optional per-call overrides (recurse, sameOriginOnly, concurrency, skippedLinks, allowedStatusCodes, basicAuth)
 *
 * @example
 * // Minimal usage
 * await page.goto('https://example.com');
 * await runLinkCheck(page);
 *
 * @example
 * // Recurse into internal links only
 * await runLinkCheck(page, { recurse: true, sameOriginOnly: true });
 */
export async function runLinkCheck(page: Page, override?: LinkCheckOverrides): Promise<void> {
  const startUrl = page.url();
  if (!startUrl) {
    throw new Error('runLinkCheck: page.url() is empty. Did you call page.goto(...) first?');
  }

  const merged = {
    ...linkCheckConfig,
    ...(override ?? {}),
    skippedLinks: {
      ...linkCheckConfig.skippedLinks,
      ...(override?.skippedLinks ?? {}),
    },
    allowedStatusCodes: {
      ...linkCheckConfig.allowedStatusCodes,
      ...(override?.allowedStatusCodes ?? {}),
    },
  };

  await pwt.step(`Link check on ${startUrl}`, async () => {
    const checker = new LinkChecker();
    const startOrigin = toOrigin(startUrl);
    const crawlerHeaders = await resolveCrawlerHeaders(page, startUrl, {
      basicAuthOverride: override?.basicAuth,
      sameOriginOnly: merged.sameOriginOnly,
    });

    const result = await checker.check({
      path: startUrl,
      recurse: merged.recurse,
      concurrency: merged.concurrency,
      timeout: merged.timeoutMs,
      headers: crawlerHeaders,
    });

    const okLinks = result.links.filter((l: any) => l.state === 'OK');
    const limitedOk =
      merged.okLinksReportLimit && merged.okLinksReportLimit > 0
        ? okLinks.slice(0, merged.okLinksReportLimit)
        : okLinks;

    const skippedLinks = result.links
      .filter((l: any) => {
        const url = l.url ?? '';
        if (!url) return false;
        return shouldSkipByPattern(url, merged.skippedLinks);
      })
      .map((l: any) => ({
        url: l.url,
        status: l.status,
        state: l.state,
      }));

    const broken = result.links
      .filter((l: any) => l.state === 'BROKEN')
      .filter((l: any) => {
        const url = l.url ?? '';
        if (!url) return true;

        if (shouldSkipByPattern(url, merged.skippedLinks)) return false;

        if (merged.sameOriginOnly) {
          try {
            return toOrigin(url) === startOrigin;
          } catch {
            return true;
          }
        }

        return true;
      })
      .filter((l: any) => {
        const status = typeof l.status === 'number' ? l.status : undefined;
        if (!status) return true;
        return !merged.allowedStatusCodes[status];
      });

    const limitedBroken =
      merged.brokenLinksReportLimit && merged.brokenLinksReportLimit > 0
        ? broken.slice(0, merged.brokenLinksReportLimit)
        : broken;

    const reportDir = path.resolve(buildDir, 'artifacts', 'linkCheck');
    fs.mkdirSync(reportDir, { recursive: true });
    await attachReportsLocationNote(reportDir);

    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeUrl = startUrl
      .replace(/^https?:\/\//, '')
      .replace(/\/+$/, '')
      .replace(/[^a-zA-Z0-9-_./]/g, '_')
      .replace(/\//g, '_')
      .slice(0, 120);

    const baseName = `link-check_${safeUrl}_${stamp}`;
    const jsonPath = path.resolve(reportDir, `${baseName}.json`);
    const mdPath = path.resolve(reportDir, `${baseName}.md`);

    const reportPayload = {
      startedAt: stamp,
      url: startUrl,
      config: {
        recurse: merged.recurse,
        sameOriginOnly: merged.sameOriginOnly,
        concurrency: merged.concurrency,
        timeoutMs: merged.timeoutMs,
        basicAuth: override?.basicAuth ?? !!crawlerHeaders?.Authorization,
        reusedSessionCookies: Boolean(crawlerHeaders?.Cookie),
        skippedLinks: merged.skippedLinks,
        allowedStatusCodes: merged.allowedStatusCodes,
        includeOkLinksInReport: merged.includeOkLinksInReport,
        okLinksReportLimit: merged.okLinksReportLimit,
        brokenLinksReportLimit: merged.brokenLinksReportLimit,
      },
      summary: {
        okCount: okLinks.length,
        brokenCount: broken.length,
        skippedCount: skippedLinks.length,
      },
      brokenLinks: limitedBroken.map((l: any) => ({
        url: l.url,
        status: l.status,
        state: l.state,
        failureDetails: l.failureDetails,
      })),
      skippedLinks,
      okLinks: merged.includeOkLinksInReport
        ? limitedOk.map((l: any) => ({
            url: l.url,
            status: l.status,
            state: l.state,
          }))
        : undefined,
    };

    const generatedOn = new Date().toLocaleString('pl-PL');

    const md = [
      `# Link Check Report  `,
      `*Generated on ${generatedOn}*`,
      ``,
      `**URL:** ${startUrl}`,
      ``,
      `## Summary`,
      ``,
      `| Metric | Count |`,
      `|--------|------:|`,
      `| OK | ${okLinks.length} |`,
      `| Broken | ${broken.length} |`,
      `| Skipped | ${skippedLinks.length} |`,
      ``,
      `---`,
      ``,
      `## Broken links`,
      broken.length
        ? limitedBroken
            .map((l: any) => {
              const note = formatFailureDetails(l.failureDetails);
              const suffix = note ? ` (${note})` : '';
              return `- ${l.url} -> ${l.status ?? 'unknown'}${suffix}`;
            })
            .join('\n')
        : 'OK _None_',
      broken.length && limitedBroken.length !== broken.length
        ? `\n\n_(showing first ${limitedBroken.length} of ${broken.length})_`
        : '',
      ``,
      skippedLinks.length ? `---\n\n## Skipped links` : undefined,
      skippedLinks.length ? skippedLinks.map((l: any) => `- ${l.url}`).join('\n') : undefined,
      ``,
      merged.includeOkLinksInReport ? `---\n\n## OK links` : undefined,
      merged.includeOkLinksInReport
        ? okLinks.length
          ? limitedOk
              .map((l: any) => `- ${l.url} -> ${typeof l.status === 'number' ? l.status : 'OK'}`)
              .join('\n')
          : 'OK _None_'
        : undefined,
      merged.includeOkLinksInReport && okLinks.length && limitedOk.length !== okLinks.length
        ? `\n\n_(showing first ${limitedOk.length} of ${okLinks.length})_`
        : undefined,
      ``,
    ]
      .filter((x): x is string => typeof x === 'string')
      .join('\n');

    fs.writeFileSync(jsonPath, JSON.stringify(reportPayload, null, 2), 'utf8');
    fs.writeFileSync(mdPath, md, 'utf8');

    try {
      await pwt.info().attach(`link-check_${safeUrl}.json`, {
        path: jsonPath,
      });

      await pwt.info().attach(`link-check_${safeUrl}.md`, {
        path: mdPath,
      });
    } catch {
      // ignore attachment errors to avoid hiding real results
    }

    if (broken.length > 0) {
      expect
        .soft(
          broken.length,
          `Broken links found on ${startUrl}: broken=${broken.length}` +
            `\n\nIssues:\n${limitedBroken
              .map((l: any) => {
                const note = formatFailureDetails(l.failureDetails);
                const suffix = note ? ` (${note})` : '';
                return `  - ${l.url} -> ${l.status ?? 'unknown'}${suffix}`;
              })
              .join('\n')}` +
            `\n\nDetailed reports saved to:\n  ${jsonPath}\n  ${mdPath}` +
            `\n\nMore link check reports can be found at:\n  ${reportDir}`
        )
        .toBe(0);
    }
  });
}
