import { expect, Page, test as pwt } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { HtmlValidate } from './htmlValidateShim';

import { htmlValidatorConfig } from '@config/feature-config/htmlValidator.config';
import { buildDir } from '@root/playwright.config';

export type HtmlValidateOverrides = {
  /** Override html-validate presets used as `extends`. */
  presets?: string[];

  /** Override html-validate rules (`true`=enabled, `false`=disabled). */
  rules?: Record<string, boolean>;

  /** Ignore selected ruleIds in reporting/failing (`true` = ignore). */
  ignoredRules?: Record<string, boolean>;

  /** Include full HTML in JSON report (can be large). */
  includeHtmlInReport?: boolean;
};

type HtmlValidateIssue = {
  ruleId: string;
  message: string;
  severity: 'error' | 'warning';
  line?: number;
  column?: number;
  selector?: string;
};

function buildMarkdown(url: string, issues: HtmlValidateIssue[]): string {
  const generatedOn = new Date().toLocaleString('pl-PL');

  const errors = issues.filter(i => i.severity === 'error');
  const warnings = issues.filter(i => i.severity === 'warning');

  const rows = issues
    .map(i => {
      const loc = typeof i.line === 'number' ? `${i.line}:${i.column ?? 0}` : '-';
      return `| ${i.severity.toUpperCase()} | ${i.ruleId} | ${loc} | ${i.message} |`;
    })
    .join('\n');

  return [
    `# HTML Validation Report  `,
    `*Generated on ${generatedOn}*`,
    ``,
    `**URL:** ${url}`,
    ``,
    `## Summary`,
    ``,
    `| Metric | Count |`,
    `|--------|------:|`,
    `| Errors | ${errors.length} |`,
    `| Warnings | ${warnings.length} |`,
    `| Total | ${issues.length} |`,
    ``,
    `---`,
    ``,
    `## Issues`,
    issues.length
      ? [
          `| Severity | Rule | Location | Message |`,
          `|----------|------|----------|---------|`,
          rows,
        ].join('\n')
      : 'OK _None_',
    ``,
  ].join('\n');
}

async function attachReportsLocationNote(reportDir: string): Promise<void> {
  try {
    const note = [
      '# HTML validator reports location',
      '',
      `More detailed HTML validator reports are available in: \`${reportDir}\``,
      '',
      'What you can find there:',
      '- per-page reports generated by each check run (including `html-validate_<url>_<timestamp>.md` and matching JSON files),',
      '- aggregated summary reports generated in teardown for the whole run:',
      '  - `html-validate-report.json`',
      '  - `html-validate-report.md`',
      '  - `html-validate-report.pdf`',
    ].join('\n');

    await pwt.info().attach('html-validator-reports-location.md', {
      body: Buffer.from(note, 'utf8'),
      contentType: 'text/markdown',
    });
  } catch {
    // ignore attachment errors to avoid hiding real results
  }
}

/**
 * Validate rendered HTML for the current page and write a report under `build/artifacts/htmlValidator/`.
 *
 * HTML validation issues are always reported as soft assertions.
 *
 * @param page Playwright Page (must already be navigated; page.url() must be non-empty)
 * @param overrides Optional per-call overrides (presets, rules, ignoredRules, includeHtmlInReport)
 *
 * @example
 * // Minimal usage
 * await page.goto('https://example.com');
 * await runHtmlValidate(page);
 *
 * @example
 * // Override rules for a single test
 * await runHtmlValidate(page, {
 *   ignoredRules: { 'void-style': true },
 * });
 */
export async function runHtmlValidate(
  page: Page,
  overrides?: HtmlValidateOverrides
): Promise<void> {
  const url = page.url();
  if (!url) throw new Error('runHtmlValidate: url is empty. Did you call page.goto(...) first?');

  const merged = {
    ...htmlValidatorConfig,
    ...(overrides ?? {}),
    presets: overrides?.presets ?? htmlValidatorConfig.presets,
    rules: {
      ...htmlValidatorConfig.rules,
      ...(overrides?.rules ?? {}),
    },
    ignoredRules: {
      ...htmlValidatorConfig.ignoredRules,
      ...(overrides?.ignoredRules ?? {}),
    },
  };

  await pwt.step(`HTML validate on ${url}`, async () => {
    const html = await page.content();

    const rules = Object.fromEntries(
      Object.entries(merged.rules).map(([ruleId, enabled]) => [ruleId, enabled ? 'error' : 'off'])
    ) as any;

    const validator = new HtmlValidate();

    const report = await validator.validateString(html, {
      extends: [...(merged.presets ?? ['html-validate:recommended'])],
      rules,
    });

    const allIssues: HtmlValidateIssue[] = report.results
      .flatMap((r: any) => r.messages)
      .map((m: any) => ({
        ruleId: String(m.ruleId ?? 'unknown'),
        message: String(m.message ?? ''),
        severity: m.severity === 2 ? 'error' : 'warning',
        line: m.line,
        column: m.column,
        selector: typeof (m as any).selector === 'string' ? (m as any).selector : undefined,
      }));

    const issues = allIssues.filter(i => !merged.ignoredRules?.[i.ruleId]);
    const errors = issues.filter(i => i.severity === 'error');

    const reportDir = path.resolve(buildDir, 'artifacts', 'htmlValidator');
    fs.mkdirSync(reportDir, { recursive: true });
    await attachReportsLocationNote(reportDir);

    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeUrl = url
      .replace(/^https?:\/\//, '')
      .replace(/\/+$/, '')
      .replace(/[^a-zA-Z0-9-_./]/g, '_')
      .replace(/[\/]/g, '_')
      .slice(0, 120);

    const baseName = `html-validate_${safeUrl}_${stamp}`;
    const jsonPath = path.resolve(reportDir, `${baseName}.json`);
    const mdPath = path.resolve(reportDir, `${baseName}.md`);

    const payload = {
      startedAt: stamp,
      url,
      config: {
        presets: merged.presets,
        rules: merged.rules,
        ignoredRules: merged.ignoredRules,
        includeHtmlInReport: merged.includeHtmlInReport,
      },
      summary: {
        errors: errors.length,
        warnings: issues.length - errors.length,
        total: issues.length,
      },
      issues,
      html: merged.includeHtmlInReport ? html : undefined,
    };

    fs.writeFileSync(jsonPath, JSON.stringify(payload, null, 2), 'utf8');
    fs.writeFileSync(mdPath, buildMarkdown(url, issues), 'utf8');

    try {
      await pwt.info().attach(`html-validate_${safeUrl}.json`, {
        path: jsonPath,
      });
      await pwt.info().attach(`html-validate_${safeUrl}.md`, {
        path: mdPath,
      });
    } catch {
      // ignore attachment errors to avoid hiding real results
    }

    if (errors.length) {
      const lines = issues.map((i, idx) => {
        const loc = typeof i.line === 'number' ? `${i.line}:${i.column ?? 0}` : '-';
        return `${idx + 1}) [${i.severity}] ${i.ruleId} @ ${loc} - ${i.message}`;
      });

      expect
        .soft(
          errors.length,
          `HTML validation errors found on ${url}: errors=${errors.length}, warnings=${issues.length - errors.length}` +
            `\n\nIssues:\n${lines.join('\n')}` +
            `\n\nDetailed reports saved to:\n  ${jsonPath}\n  ${mdPath}` +
            `\n\nMore HTML validator reports can be found at:\n  ${reportDir}`
        )
        .toBe(0);
    }
  });
}
