import { expect, Page, test as pwt } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

import { buildDir } from '@root/playwright.config';
import { assertNoConsoleErrorsConfig } from '@config/feature-config/assertNoConsoleErrors.config';
import { waitForPageIdle } from '@utils/waitForPageIdle';

type ConsoleCheckTarget =
  | string
  | {
      goto: () => Promise<void>;
      getFullPageUrl?: () => string;
      getPageUrl?: () => string;
    };

export type AssertNoConsoleErrorsOverrides = {
  ignoredPatternsOverride?: Record<string, boolean>;
  includeConsoleMessagesInReport?: boolean;
};

async function attachReportsLocationNote(reportDir: string): Promise<void> {
  try {
    const note = [
      '# Console errors reports location',
      '',
      `More detailed console errors reports are available in: \`${reportDir}\``,
      '',
      'What you can find there:',
      '- per-page reports generated by each check run (including `console-errors_<url>_<timestamp>.md` and matching JSON files),',
      '- aggregated summary reports generated in teardown for the whole run:',
      '  - `console-errors-report.json`',
      '  - `console-errors-report.md`',
      '  - `console-errors-report.pdf`',
    ].join('\n');

    await pwt.info().attach('console-errors-reports-location.md', {
      body: Buffer.from(note, 'utf8'),
      contentType: 'text/markdown',
    });
  } catch {
    // ignore attachment errors to avoid hiding real results
  }
}

/**
 * Assert that no non-ignored console errors appear while loading a page.
 *
 * Console issues are always reported as soft assertions.
 *
 * @param page Playwright Page
 * @param target URL string, or a POM object with `goto()` (and optional `getFullPageUrl()`/`getPageUrl()`)
 * @param options Optional per-call overrides (ignoredPatternsOverride, includeConsoleMessagesInReport)
 *
 * @example
 * // Minimal usage
 * await assertNoConsoleErrors(page, 'https://example.com');
 *
 * @example
 * // With a POM target and ignored pattern override
 * await assertNoConsoleErrors(page, homePage, {
 *   ignoredPatternsOverride: { 'ResizeObserver loop': true },
 * });
 */
export async function assertNoConsoleErrors(
  page: Page,
  target: ConsoleCheckTarget,
  options?: AssertNoConsoleErrorsOverrides
): Promise<void> {
  const mergedIgnoredPatterns: Record<string, boolean> = {
    ...assertNoConsoleErrorsConfig.ignoredPatterns,
    ...(options?.ignoredPatternsOverride ?? {}),
  };
  const includeConsoleMessagesInReport =
    options?.includeConsoleMessagesInReport ??
    assertNoConsoleErrorsConfig.includeConsoleMessagesInReport;

  const targetLabel =
    typeof target === 'string'
      ? target
      : (target.getFullPageUrl?.() ?? target.getPageUrl?.() ?? '[pom target]');

  await pwt.step(`Assert no console errors on ${targetLabel}`, async () => {
    const errors: string[] = [];

    const handler = (msg: any): void => {
      if (msg.type() === 'error') {
        const text = msg.text();
        const shouldIgnore = Object.entries(mergedIgnoredPatterns).some(
          ([pattern, enabled]) => enabled && text.includes(pattern)
        );
        if (!shouldIgnore) errors.push(text);
      }
    };

    page.on('console', handler);
    try {
      if (typeof target === 'string') {
        await page.goto(target);
      } else {
        await target.goto();
      }
      await waitForPageIdle(page);
    } finally {
      page.off('console', handler);
    }

    const url = page.url();

    const reportDir = path.resolve(buildDir, 'artifacts', 'assertNoConsoleErrors');
    fs.mkdirSync(reportDir, { recursive: true });
    await attachReportsLocationNote(reportDir);

    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeUrl = url
      .replace(/^https?:\/\//, '')
      .replace(/\/+$/, '')
      .replace(/[^a-zA-Z0-9-_./]/g, '_')
      .replace(/[\/]/g, '_')
      .slice(0, 120);

    const baseName = `console-errors_${safeUrl}_${stamp}`;
    const jsonPath = path.resolve(reportDir, `${baseName}.json`);
    const mdPath = path.resolve(reportDir, `${baseName}.md`);

    const payload = {
      startedAt: stamp,
      url,
      config: {
        ignoredPatterns: mergedIgnoredPatterns,
        includeConsoleMessagesInReport,
      },
      summary: {
        errors: errors.length,
      },
      errors: includeConsoleMessagesInReport ? errors : undefined,
    };

    const generatedOn = new Date().toLocaleString('pl-PL');
    const md = [
      `# Console Errors Report  `,
      `*Generated on ${generatedOn}*`,
      ``,
      `**URL:** ${url}`,
      ``,
      `## Summary`,
      ``,
      `| Metric | Count |`,
      `|--------|------:|`,
      `| Errors | ${errors.length} |`,
      ``,
      `---`,
      ``,
      `## Errors`,
      errors.length ? errors.map((e, i) => `${i + 1}) ${e}`).join('\n') : 'OK _None_',
      ``,
    ].join('\n');

    fs.writeFileSync(jsonPath, JSON.stringify(payload, null, 2), 'utf8');
    fs.writeFileSync(mdPath, md, 'utf8');

    try {
      await pwt.info().attach(`console-errors_${safeUrl}.json`, {
        path: jsonPath,
      });
      await pwt.info().attach(`console-errors_${safeUrl}.md`, {
        path: mdPath,
      });
    } catch {
      // ignore attachment errors to avoid hiding real results
    }

    if (errors.length > 0) {
      const details = errors.map((e, index) => `  [${index + 1}] ${e}`).join('\n');
      expect
        .soft(
          errors.length,
          `Console errors found on ${url}: errors=${errors.length}` +
            `\n\nIssues:\n${details}` +
            `\n\nDetailed reports saved to:\n  ${jsonPath}\n  ${mdPath}` +
            `\n\nMore console errors reports can be found at:\n  ${reportDir}`
        )
        .toBe(0);
    }
  });
}
