import { expect, Page, test as pwt } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

import { buildDir } from '@root/playwright.config';
import { accessibilityConfig } from '@config/feature-config/accessibility.config';
import AxeBuilder from './axeShim';

export type AccessibilityOverrides = {
  tags?: string[];
  ignoredRules?: Record<string, boolean>;
  excludeElements?: string[];
  includeNodesInReport?: boolean;
};

type AccessibilityIssue = {
  id: string;
  impact?: string;
  description: string;
  help: string;
  helpUrl: string;
  tags: string[];
  nodes: string[];
};

async function attachReportsLocationNote(reportDir: string): Promise<void> {
  try {
    const note = [
      '# Accessibility reports location',
      '',
      `More detailed accessibility reports are available in: \`${reportDir}\``,
      '',
      'What you can find there:',
      '- per-page reports generated by each check run (including `accessibility_<url>_<timestamp>.md` and matching JSON files),',
      '- aggregated summary reports generated in teardown for the whole run:',
      '  - `accessibility-report.json`',
      '  - `accessibility-report.md`',
      '  - `accessibility-report.pdf`',
    ].join('\n');

    await pwt.info().attach('accessibility-reports-location.md', {
      body: Buffer.from(note, 'utf8'),
      contentType: 'text/markdown',
    });
  } catch {
    // ignore attachment errors to avoid hiding real results
  }
}

/**
 * Runs an accessibility (axe-core) scan on the current page and writes a report under `build/artifacts/accessibility/`.
 *
 * Accessibility violations are always reported as soft assertions — the test continues even when issues are found.
 *
 * @param page Playwright Page (must already be navigated; page.url() must be non-empty)
 * @param overrides Optional per-call overrides (tags, ignoredRules, excludeElements, includeNodesInReport)
 *
 * @example
 * // Minimal usage
 * await page.goto('https://example.com');
 * await runAccessibilityCheck(page);
 *
 * @example
 * // Override tags and exclude elements for a single test
 * await runAccessibilityCheck(page, {
 *   tags: ['wcag2a', 'wcag2aa'],
 *   excludeElements: ['#third-party-widget'],
 * });
 */
export async function runAccessibilityCheck(
  page: Page,
  overrides?: AccessibilityOverrides
): Promise<void> {
  const url = page.url();
  if (!url)
    throw new Error('runAccessibilityCheck: url is empty. Did you call page.goto(...) first?');

  const merged = {
    ...accessibilityConfig,
    ...(overrides ?? {}),
    tags: overrides?.tags ?? accessibilityConfig.tags,
    ignoredRules: {
      ...accessibilityConfig.ignoredRules,
      ...(overrides?.ignoredRules ?? {}),
    },
    excludeElements: [
      ...accessibilityConfig.excludeElements,
      ...(overrides?.excludeElements ?? []),
    ],
  };

  await pwt.step(`Accessibility scan on ${url}`, async () => {
    const disabledRules = Object.entries(merged.ignoredRules)
      .filter(([, ignore]) => ignore)
      .map(([ruleName]) => ruleName);

    let axeBuilder = new AxeBuilder({ page })
      .withTags([...merged.tags])
      .disableRules(disabledRules);

    for (const selector of merged.excludeElements) {
      axeBuilder = axeBuilder.exclude(selector);
    }

    const results = await axeBuilder.analyze();

    const issues: AccessibilityIssue[] = (results.violations ?? []).map((v: any) => ({
      id: String(v.id ?? 'unknown'),
      impact: typeof v.impact === 'string' ? v.impact : undefined,
      description: String(v.description ?? ''),
      help: String(v.help ?? ''),
      helpUrl: String(v.helpUrl ?? ''),
      tags: Array.isArray(v.tags) ? v.tags.map((t: any) => String(t)) : [],
      nodes: merged.includeNodesInReport
        ? (Array.isArray(v.nodes) ? v.nodes : []).flatMap((n: any) =>
            Array.isArray(n.target) ? n.target.filter((x: any) => typeof x === 'string') : []
          )
        : [],
    }));

    const reportDir = path.resolve(buildDir, 'artifacts', 'accessibility');
    fs.mkdirSync(reportDir, { recursive: true });
    await attachReportsLocationNote(reportDir);

    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeUrl = url
      .replace(/^https?:\/\//, '')
      .replace(/\/+$/, '')
      .replace(/[^a-zA-Z0-9-_./]/g, '_')
      .replace(/[\/]/g, '_')
      .slice(0, 120);

    const baseName = `accessibility_${safeUrl}_${stamp}`;
    const jsonPath = path.resolve(reportDir, `${baseName}.json`);
    const mdPath = path.resolve(reportDir, `${baseName}.md`);

    const impactCounts = {
      critical: issues.filter(i => i.impact === 'critical').length,
      serious: issues.filter(i => i.impact === 'serious').length,
      moderate: issues.filter(i => i.impact === 'moderate').length,
      minor: issues.filter(i => i.impact === 'minor').length,
    };

    const payload = {
      startedAt: stamp,
      url,
      config: {
        tags: merged.tags,
        ignoredRules: merged.ignoredRules,
        excludeElements: merged.excludeElements,
        includeNodesInReport: merged.includeNodesInReport,
      },
      summary: {
        violations: issues.length,
        ...impactCounts,
      },
      violations: issues,
    };

    const generatedOn = new Date().toLocaleString('pl-PL');
    const md = [
      `# Accessibility Report  `,
      `*Generated on ${generatedOn}*`,
      ``,
      `**URL:** ${url}`,
      ``,
      `## Summary`,
      ``,
      `| Metric | Count |`,
      `|--------|------:|`,
      `| Violations | ${issues.length} |`,
      `| Critical | ${impactCounts.critical} |`,
      `| Serious | ${impactCounts.serious} |`,
      `| Moderate | ${impactCounts.moderate} |`,
      `| Minor | ${impactCounts.minor} |`,
      ``,
      `---`,
      ``,
      `## Violations`,
      issues.length
        ? issues
            .map(issue => {
              const nodes = issue.nodes.length
                ? `\n  Nodes:\n${issue.nodes.map(n => `  - ${n}`).join('\n')}`
                : '';
              return `- [${issue.impact ?? 'unknown'}] ${issue.id} - ${issue.help}${nodes}`;
            })
            .join('\n')
        : 'OK _None_',
      ``,
    ].join('\n');

    fs.writeFileSync(jsonPath, JSON.stringify(payload, null, 2), 'utf8');
    fs.writeFileSync(mdPath, md, 'utf8');

    try {
      await pwt.info().attach(`accessibility_${safeUrl}.json`, { path: jsonPath });
      await pwt.info().attach(`accessibility_${safeUrl}.md`, { path: mdPath });
    } catch {
      // ignore attachment errors to avoid hiding real results
    }

    if (issues.length > 0) {
      expect
        .soft(
          issues.length,
          `Accessibility violations found on ${url}: violations=${issues.length}` +
            `\n\nDetailed reports saved to:\n  ${jsonPath}\n  ${mdPath}` +
            `\n\nMore accessibility reports can be found at:\n  ${reportDir}`
        )
        .toBe(0);
    }
  });
}
